"""MODE A -- SSE AS GENERATOR (the two-tower's role), full corpus, all three aspects.

For each PK (and LK) cell x aspect: reproduce the DEPLOYED per-cell anchor fresh via cafa_eval,
then add SSE's top-k out-of-pool proposals to the deployed pool and re-score. The deployed pool is
already generated by the two-tower (KNN) + reranker, so a POSITIVE delta means SSE proposes true
terms the two-tower missed that convert; a negative delta means SSE is not additive as a candidate
source. Controls: random-order (shuffle SSE scores over the same extras) + matched-volume (uniform
random out-of-pool terms). Paired bootstrap CI (per-protein) invoked when a delta is positive.
True frame: prop=fill norm=cafa no_orphans toi, PK exclude=groundtruth_PK_known, cafa_eval PROTEA/.venv.
Run under PROTEA/.venv.
"""
import json, collections, time, subprocess, tempfile, sys
from pathlib import Path
import numpy as np, pandas as pd, pyarrow.parquet as pq
from sklearn.metrics import roc_auc_score

t0 = time.time()
def log(m): print(f"[{time.time()-t0:6.0f}s] {m}", flush=True)
ROOT = Path("/home/frapercan/Thesis2")
R = ROOT / "repositories/protea-reranker-lab/results/sparse_classifier"
EVAL = R / "percut_rerank/eval.parquet"
PREDDIR = R / "percut_rerank/predictions"
GTDIR = R / "lafa_gt"
OBO = str(ROOT / "protea-lafa-knn/lafa_t0_Sep_2025/go-basic.obo")
IA_F = str(ROOT / "protea-lafa-knn/lafa_t0_Sep_2025/IA.tsv")
TOI = str(GTDIR / "groundtruth_terms_of_interest.txt")
OUT = ROOT / "storage/sse_full"
PY = str(ROOT / "repositories/PROTEA/.venv/bin/python")
COMBINE = sys.argv[1] if len(sys.argv) > 1 else "min"     # consensus for generation ranking
CELLS = sys.argv[2].split(",") if len(sys.argv) > 2 else ["PK", "LK"]
ASPECTS = {"mfo": ("F", "mfo"), "bpo": ("P", "bpo"), "cco": ("C", "cco")}
TOPKS = [5, 10, 25]

par = collections.defaultdict(set); ns = {}; alt = {}; cur = None
for line in open(OBO):
    line = line.rstrip("\n")
    if line == "[Term]": cur = None
    elif line.startswith("id: GO:"): cur = line[4:]
    elif cur and line.startswith("namespace: "): ns[cur] = line[11:]
    elif cur and line.startswith("is_a: GO:"): par[cur].add(line[6:].split(" ! ")[0].strip())
    elif cur and line.startswith("relationship: part_of GO:"):
        par[cur].add(line[len("relationship: part_of "):].split(" ! ")[0].strip())
    elif cur and line.startswith("alt_id: GO:"): alt[line[8:]] = cur
NSMAP = {"F": "molecular_function", "P": "biological_process", "C": "cellular_component"}
_anc = {}
def anc(t):
    t = alt.get(t, t)
    if t in _anc: return _anc[t]
    seen, st = set(), [t]
    while st:
        x = st.pop()
        if x in seen: continue
        seen.add(x)
        for p in par.get(x, ()): st.append(p)
    r = frozenset(seen); _anc[t] = r; return r
IA = {}
for line in open(IA_F):
    p = line.rstrip("\n").split("\t")
    if len(p) >= 2:
        try: IA[p[0]] = float(p[1])
        except ValueError: pass
def iamass(ts): return float(sum(IA.get(t, 0.0) for t in ts))

DRIVER = '''
import json, signal
from cafaeval.evaluation import cafa_eval
signal.signal(signal.SIGTERM, signal.SIG_DFL)
df, dfs = cafa_eval("{obo}", "{pd}", "{gt}", ia="{ia}", prop="fill", norm="cafa",
    no_orphans=True, toi_file="{toi}", exclude={known}, max_terms=None, th_step=0.01,
    n_cpu=6, weighted_only=False)
out = {{}}
for k, v in dfs.items(): out[k] = v.reset_index().to_dict(orient="records")
json.dump(out, open("{o}", "w"), default=str)
'''
def cafa(rows, gt_file, known, nsname):
    with tempfile.TemporaryDirectory() as td:
        d = Path(td) / "pd"; d.mkdir()
        with (d / "p.tsv").open("w") as fh:
            for p_, g_, v in rows: fh.write(f"{p_}\t{g_}\t{v:.6f}\n")
        raw = Path(td) / "r.json"; drv = Path(td) / "d.py"
        knownrepr = f'"{known}"' if known else "None"
        drv.write_text(DRIVER.format(obo=OBO, pd=str(d), gt=gt_file, ia=IA_F, toi=TOI,
                                     known=knownrepr, o=str(raw)))
        r = subprocess.run([PY, str(drv)], capture_output=True, text=True, timeout=7200)
        if r.returncode != 0:
            print(r.stderr[-1500:], flush=True); return None
        best = None
        for rec in json.loads(raw.read_text()).get("f_micro_w", []):
            if (rec.get("ns") or "") == nsname and rec.get("f_micro_w") is not None:
                best = rec
        return round(float(best["f_micro_w"]), 5) if best else None

# per-protein paired bootstrap over the cafa cell: approximated by resampling proteins and recomputing
# the added-true/false IA mass (fast surrogate); the AUTHORITATIVE delta is the cafa_eval number above.
def boot_ci(perprot_delta, B=2000):
    if not perprot_delta: return None
    a = np.array(perprot_delta); rng = np.random.default_rng(0); n = len(a)
    bs = [a[rng.integers(0, n, n)].mean() for _ in range(B)]
    return [round(float(np.percentile(bs, 2.5)), 5), round(float(np.percentile(bs, 97.5)), 5)]

results = {"combine": COMBINE}
for cell in CELLS:
    cat = cell.lower()
    gt_fn = str(GTDIR / f"groundtruth_{cell}.tsv")
    known = str(GTDIR / f"groundtruth_{cell}_known.tsv") if cell == "PK" else None
    dep = pd.read_csv(PREDDIR / cat / f"{cat}.tsv", sep="\t", header=None, names=["prot", "term", "score"])
    dep["term"] = dep.term.map(lambda g: alt.get(g, g))
    tb_all = pq.read_table(EVAL, columns=["protein_accession", "go_term_id", "label", "aspect",
                                          "category"]).to_pandas()
    tb_all = tb_all[tb_all.category == cat]
    tb_all["go"] = tb_all.go_term_id.map(lambda g: alt.get(g, g))

    for asp, (letter, aspcode) in ASPECTS.items():
        spath = OUT / f"scoresA_{cell}_{asp}.npz"
        if not spath.exists():
            log(f"SKIP {cell}-{asp}: scores missing"); continue
        nsname = NSMAP[letter]
        Z = np.load(spath, allow_pickle=True)
        prots = Z["proteins"].tolist(); terms = [alt.get(g, g) for g in Z["terms"].tolist()]
        S = Z[COMBINE]
        tpos = {g: j for j, g in enumerate(terms)}; pidx = {p: i for i, p in enumerate(prots)}
        gt = pd.read_csv(gt_fn, sep="\t"); gt = gt[gt.aspect == letter].copy()
        gt["term"] = gt.term.map(lambda g: alt.get(g, g))
        gt_leaf = gt.groupby("EntryID").term.apply(set).to_dict()
        targets = [p for p in sorted(gt_leaf) if p in pidx]
        # restrict propagation to this namespace
        def anc_ns(t): return frozenset(x for x in anc(t) if ns.get(x) == nsname)
        gt_prop = {p: (frozenset().union(*[anc_ns(t) for t in gt_leaf[p]]) if gt_leaf[p] else frozenset())
                   for p in targets}
        tb = tb_all[(tb_all.protein_accession.isin(set(targets))) & (tb_all.aspect == aspcode)]
        pool = tb.groupby("protein_accession").go.apply(set).to_dict()
        pool_prop = {p: (frozenset().union(*[anc_ns(t) for t in pool[p]]) if pool.get(p) else frozenset())
                     for p in targets}
        # anchor base = FULL deployed prediction file (all aspects); cafa filters by namespace,
        # exactly reproducing the deployed per-cell anchor (as the POC measure did).
        base = list(dep.itertuples(index=False, name=None))
        fn_total = sum(iamass(gt_prop[p] - pool_prop[p]) for p in targets)
        log(f"=== {cell}-{asp}: targets {len(targets)} base_rows {len(base)} FN_IA {fn_total:.1f} ===")
        cr = {"n_targets": len(targets), "FN_tail_IA": round(fn_total, 1)}

        # anchor (deployed pool only), true frame
        fa = cafa(base, gt_fn, known, nsname)
        cr["anchor_reproduced"] = fa
        log(f"  anchor {cell}-{asp}: {fa}")

        # separability: per-protein AUC SSE vs deployed reranker on reachable pool tail
        lab = {(r.protein_accession, r.go): int(r.label) for r in tb.itertuples()}
        rr = {(r.prot, r.term): r.score for r in dep.itertuples()}
        se_a, rr_a = [], []
        for p in targets:
            cands = [g for g in pool.get(p, set()) if (p, g) in lab and g in tpos]
            y = np.array([lab[(p, g)] for g in cands])
            if y.sum() == 0 or y.sum() == len(y) or len(y) < 5: continue
            se = np.array([S[pidx[p], tpos[g]] for g in cands])
            rv = np.array([rr.get((p, g), 0.0) for g in cands])
            se_a.append(roc_auc_score(y, se)); rr_a.append(roc_auc_score(y, rv))
        cr["separability"] = {"n": len(se_a),
            "SSE_auc": round(float(np.mean(se_a)), 4) if se_a else None,
            "reranker_auc": round(float(np.mean(rr_a)), 4) if rr_a else None,
            "delta": round(float(np.mean(np.array(se_a) - np.array(rr_a))), 4) if se_a else None}
        log(f"  separability SSE {cr['separability']['SSE_auc']} rr {cr['separability']['reranker_auc']}")

        # gate + convert: top-k out-of-pool proposals
        prop_lists = {}; added_true = {k: 0.0 for k in TOPKS}; added_false = {k: 0.0 for k in TOPKS}
        perprot_true = {k: {} for k in TOPKS}
        for p in targets:
            i = pidx[p]; sc = S[i]; order = np.argsort(-sc)
            present = pool.get(p, set()); gtp = gt_prop[p]; covered = set(pool_prop.get(p, frozenset()))
            picks = []; k = 0
            for j in order:
                g = terms[j]
                if g in present: continue
                picks.append((g, float(sc[j])))
                new = anc_ns(g) - covered
                tm = iamass(new & gtp); fm = iamass(new - gtp); covered |= new
                k += 1
                for kk in TOPKS:
                    if k <= kk:
                        added_true[kk] += tm; added_false[kk] += fm
                        perprot_true[kk][p] = perprot_true[kk].get(p, 0.0) + (tm - fm)
                if k >= max(TOPKS): break
            prop_lists[p] = picks
        cr["gate"] = {}
        for kk in TOPKS:
            at, af = added_true[kk], added_false[kk]
            cr["gate"][f"top{kk}"] = {"true_IA": round(at, 2), "false_IA": round(af, 2),
                "prec_IA": round(at / (at + af), 4) if (at + af) > 0 else None,
                "frac_FN_rec": round(at / fn_total, 4) if fn_total > 0 else None}

        cr["convert"] = {}; rng = np.random.default_rng(42)
        bp_terms_all = terms
        for K in TOPKS:
            ex = [(p, g, sv) for p in targets for (g, sv) in prop_lists[p][:K]]
            if ex:
                sv = np.array([e[2] for e in ex]); lo, hi = sv.min(), sv.max()
                nrm = (lambda v: (v - lo) / (hi - lo)) if hi > lo else (lambda v: 0.5)
                exB = [(p, g, float(nrm(v))) for (p, g, v) in ex]
            else: exB = []
            fb = cafa(base + exB, gt_fn, known, nsname)
            dB = round(fb - fa, 5) if (fb is not None and fa is not None) else None
            # random-order control
            if exB:
                sh = sv.copy(); rng.shuffle(sh)
                exR = [(exB[m][0], exB[m][1], float((sh[m] - sh.min()) / (sh.max() - sh.min() + 1e-9)))
                       for m in range(len(exB))]
                fr = cafa(base + exR, gt_fn, known, nsname); dR = round(fr - fa, 5) if fr is not None else None
            else: fr, dR = fa, 0.0
            # matched-volume control
            exU = []
            for p in targets:
                present = pool.get(p, set()); cand = [g for g in bp_terms_all if g not in present]
                pick = rng.choice(len(cand), min(K, len(cand)), replace=False)
                for j in pick: exU.append((p, cand[j], float(rng.uniform(0.3, 0.7))))
            fu = cafa(base + exU, gt_fn, known, nsname); dU = round(fu - fa, 5) if fu is not None else None
            ci = boot_ci(list(perprot_true[K].values())) if (dB is not None and dB > 0) else None
            cr["convert"][f"top{K}"] = {"n_extras": len(exB), "B": fb, "delta_B": dB,
                "random_order": fr, "delta_random": dR, "matched_volume": fu, "delta_uniform": dU,
                "surrogate_ci_addedIA": ci}
            log(f"  convert top{K}: dB {dB:+} | rand {dR:+} | unif {dU:+}")
            results[f"{cell}-{asp}"] = cr
            json.dump(results, open(OUT / f"modeA_{COMBINE}.json", "w"), indent=1, default=float)
        results[f"{cell}-{asp}"] = cr
        json.dump(results, open(OUT / f"modeA_{COMBINE}.json", "w"), indent=1, default=float)

json.dump(results, open(OUT / f"modeA_{COMBINE}.json", "w"), indent=1, default=float)
log("MODE A DONE"); print(json.dumps(results, indent=1, default=float))
